### ISSUE TITLE
Inconsistent handling of 'facetable' field suffix between dynamic_schema_service, dynamic_catalog_behavior

### ISSUE THREAD

**Issue by aploshay** [samvera-labs/allinson_flex#53]
In dynamic catalog behavior, [field names are derived using `#solr_name`](https://github.com/samvera-labs/allinson_flex/blob/00cf16660517cfe4e7c967437942c0e109362b64/app/controllers/concerns/allinson_flex/dynamic_catalog_behavior.rb#L31-L36).
In the dynamic schema service, [field names are derived using a custom `#index_as` method](https://github.com/samvera-labs/allinson_flex/blob/00cf16660517cfe4e7c967437942c0e109362b64/app/services/allinson_flex/dynamic_schema_service.rb#L186-L214).

The current issue is that, while the comment documentation for `#index_as` suggest it's adding `_sim` for the `facetable` case, it's actually adding `_ssm`, which is inconsistent with the `_sim` suffix added by `#solr_name` in the catalog behavior -- so, the field does get indexed, but due to the mismatch it never shows up in the UI.

Also note that `#index_as` documents a `sortable` case but it's missing.

These are both minor typos/omissions and easily fixed, but the design question I have is: at first glance, it seems that one would want to consistently use the same method, whether that's `#solr_name` or `#index_as`, across both the indexing and catalog behaviors to ensure that this sort of disagreement isn't _possible_.  Does this inconsistency serve some current/future purpose I'm not catching onto?

**Comment by aploshay** [comment]
(Inadvertently closed this when merging in a monkeypatch to this issue, in another project)

**Comment by laritakr** [comment]
This was previously fixed in commit https://github.com/samvera-labs/allinson_flex/commit/6d20647fc1187ec58ffdb974a9d02bc1b5d77246
