### ISSUE TITLE
do not use Hyrax::BasicMetadata

### ISSUE THREAD

**Issue by alishaevn** [samvera-labs/allinson_flex#94]
# summary
the purpose of allinson_flex is so that a user can create their own metadata properties. however, Hyrax::BasicMetadata is added to each model generated through the works_generator.rb file. therefore, all properties in BasicMetadata are added to a model, whether or not they are in the metadata profile

# suggestion
- remove Hyrax::BasicMetadata from models created with allinson_flex

# resources
- https://github.com/samvera-labs/allinson_flex/blob/3eec46eea7bd8c054990a6809f6d33706e7345d1/lib/generators/allinson_flex/works_generator.rb#L96
-

**Comment by laritakr** [comment]
Resolved with #104
